name: pci-pmi-data
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.10
- pip

# Dependencies of the workflow itself
- snakemake-minimal<8.25 # See https://github.com/snakemake/snakemake/issues/3202
- yaml
- numpy
- pandas>=2.1
- geopandas>=1
- scipy
- shapely>=2.0
- geojson
- pdfplumber

# pip
- pip:
  - snakemake-storage-plugin-http
  - snakemake-executor-plugin-slurm
  - snakemake-executor-plugin-cluster-generic
